### ISSUE TITLE
Remove borders between multiselect and dropdown composition

### ISSUE THREAD

**Issue by adavidof** [wix/wix-style-react#2140]
How can I do multiselect and dropdown in one composition with only one border between them?

### Summary:
![image](https://user-images.githubusercontent.com/10529679/44217096-555ee100-a17f-11e8-99be-954e49e59fb7.png)

Current solution is weird:
```css
// fixes for inputs borders
.emailsMultiselect > div > div > div > div {
  border-top-right-radius: 0;
  border-bottom-right-radius: 0;
}

.permissionsDropdown > div > div > div {
  border-left: 0;
}
```

### Relevant Components:
Multiselect
Dropdown

**Comment by adavidof** [comment]
@shlomitc thanks, but my design is another

**Comment by shlomitc** [comment]
@hepiyellow - I remember you handled such composition.
Is it possible making the existing components to be placed one next to the other without a wrapping div that forces css styles from outside the component?
need to take into consideration the focus ring overlapping

**Comment by adavidof** [comment]
@shlomitc 
I use `noRightBorderRadius` and `noLeftBorderRadius`
But I need to remove the borders between inputs

**Comment by shlomitc** [comment]
@adavidof, yes I wrote that in the previous comment.
Also - the focus ring is overlapped by the next component, this is why I asked hepiyellow for suggestion

**Comment by hepiyellow** [comment]
Well...
## Using FieldWithSelectionComposite
 won't work, since unlike the `<Input/>` (which it expects), the `<MultiSelect/>` has a `<div/>` wrapper around the `<InputWithTags/>`, so the selector won't find the correct element that should have the border.

## "weird" solution has an issue.
 Did you try to focus the Dropdown? Because the focus ring is '3px' wide, then there is overlapping. To fix the overlapping, we need to add `z-index`. When adding `z-index`, then when the Dropdown is focused, it's left border would be missing. 

## Alternating Z-index solution - (with a *but...*)
 is to have the Dropdown with `margin: 0 0 0 -1px` (left margin -1px), so that the left and right borders overlap. And add `z-index: 2` to component which is currently focused. Unfortunately, *this can be done only in WSR code* because you can not target the `hasFocus` pseudo class (css modules)

## So...
Either:
1. We implement this in WSR. 
1. If you really need it now, you could use a [`focus-within` polyfill](https://github.com/jonathantneal/focus-within) and then you can implement the Alternating Z-index solution. It will look something like this:
```css
.permissionsDropdown {
  margin: 0 0 0 -1px;
}

.emailsMultiselect[focus-within] {
  z-index: 2;
}
.permissionsDropdown[focus-within] {
  z-index: 2;
}
```
