### ISSUE TITLE
Typography - technical specs for theming and performance improvement

### ISSUE THREAD

**Issue by shlomitc** [wix/wix-style-react#3907]
# The Wix Style React typography improvements
This issue comes to describe the current state of fonts loading in the library, point the problems that we have and suggest solutions. The priority and order of the actions will be described as well.

## Typography in the library
The Design System fonts in `wix-style-react` use the Helvetica fonts by default and fallbacks to a stack of common system fonts.

### Exposing typography
The components in the library come with the right typography by either using the `<Text/>` and `<Heading/>` components providing predefined variations or through common css mixins.

Consumers are asked to download the css definition file with all font-faces through a link tag:

```html
<link rel="stylesheet" href="//static.parastorage.com/services/third-party/fonts/Helvetica/fontFace.css">
```

### Usage internally in the library
The font style tokens and declaration sits in both SCSS file (as mixin) and stylable (as classes) and consumed directly or by other components.

For example, `<Page.Header/>` uses the `<Heading/>` component internally, while `<Input/>`'s placeholder is a SCSS mixin `@include FontRoman()`.

## Issues to tackle
The current solution works, however, there are two main topics to tackle:

1. Best practices and performance improvements in fonts loading (reduce download usages for example)
2. Allow customizing the font family (custom foreign languages for example)

Here's an example of a font face downloaded from the CSS link
```css
@font-face{
    font-family:"HelveticaNeueW02-75Bold";
    src:url("Fonts/db853e0e-929b-4272-b420-c946c954cf3a.eot?#iefix");
    src:url("Fonts/db853e0e-929b-4272-b420-c946c954cf3a.eot?#iefix") format("eot"),url("Fonts/4a9c62ab-b359-4081-8383-a0d1cdebd111.woff") format("woff"),url("Fonts/db5f9ba6-05a4-433a-9461-0a6f257a0c3a.ttf") format("truetype"),url("Fonts/25e09910-ffc3-4fc4-b0d1-db9a95dface8.svg#25e09910-ffc3-4fc4-b0d1-db9a95dface8") format("svg");
}
```

### 1. Unmaintained CSS File
The current [`fontFace.css`](https://static.parastorage.com/services/third-party/fonts/Helvetica/fontFace.css) file is not maintained, meaning there's a lot of redundant code there which is downloaded but not necessary

Also, many of the formats are not required (`svg` for example). `wuff2` should be the right format to be downloaded (30% smaller file size).

**This file can be improved and have only the necessary fonts**

### 2. Font family should not mention the weight
Currently, our css font file defines each font weight as a font name (e.g. `HelveticaNeueW02-75Bold`). The best practice is creating a single font-family name separated from the defined weights. For example:
```css
@font-face {
  font-family: 'Assistant';
  font-style: normal;
  font-weight: 600;
  font-display: swap;
  src: local('Assistant SemiBold'), local('Assistant-SemiBold'), url(https://fonts.gstatic.com/s/assistant/v4/2sDZZGJYnIjSi6H75xk7t0GsBJ0YTivYtg.woff2) format('woff2');
}
```

**This means to separate the `font-family` from the `font-weight`**

This is how the new "Wix Font" will appear, meaning we want to align with this best practice and gives value when coming to create a theme (will be explained next).

Having `font-weight` for the components themselves will also improve the look of other fonts (foreign languages for example)

### 3. Font stack is wrong
Here's a definition for one of our font family:
```scss
$fonts-fallback: "Helvetica Neue", "Helvetica", "Arial", "メイリオ, meiryo", "ヒラギノ角ゴ pro w3", "hiragino kaku gothic pro", "sans-serif";
$FontMedium: "HelveticaNeueW01-65Medi", "HelveticaNeueW02-65Medi", 
```

In this case, since `Helvetica` is common and native across many devices, we should **try first to load the native one and fallback to the custom fonts in case it doesn't exist**.

This can improve performance as the font will not have to be downloaded.

### 4. Customize font family
A rising request is customizing the font family. As the library doesn't have a built-in theming solution, this can be the first step towards a stronger theming approach.

This is important for the new "Wix Font" in order to create a single feature toggle across the system and let consumers gradually migrate without making a major version bump.

### 5. More possible improvements
* Create fonts for specific languages (when a language is changed we have a full page reload), this way we can really reduce the size of the font (omitting unneeded characters).

* Consider use variable fonts (should check browser compatibility)

* Apply "two steps font-loading strategy" to avoid FOUT / FOIT completely (flash of unstyled text/flash of invisible text). Load only the minimal subset of characters needed from the font (e.g. Latin characters for English) and later asynchronously load the full font which contains hints and all the other features of the font (e.g. 1/2 will be displayed as ½). 

* Use 'font-display' descriptor

## Additional Resources
Fonts tokens appear in multiple files across the libraries chain but should all be changed or deprecated if possible.

| Library | File |
|---|---|
| `wix-style-react`  |  `src/fonts.scss` |
| `wix-style-react`  |  `src/Foundation/stylable.st.css` |
| `wix-ui-backoffice`  |  `src/typography.st.css` |
| `wix-ui-core`  |  `src/themes/backoffice/typography.st.css` |

### Intro
In design systems, it's common to have a definition file with all the design tokens (colors, spacing, typography, etc...).
Ideally, we could allow customizing this to pallete to create multiple themes. This might not have a great benefit for out direct internal consumers but can be a nice to have and better-sturctured architecture.

Specifically, changing the font theme is more important, as it can improve the consumer experience and have great benefits when loading custom fonts for specific languages.

### The problems
1. `wix-style-react` has multiple styling solutions (`SCSS` and `Stylable`).
2. `Stylable` doesn't provide a theming mechanism replacing a tokens file, only targeting components.
3. Theming solution of `SCSS` and `CSSModules` doesn't exist out of the box. It requires integrating a third-party tool like [`react-css-themr`](https://github.com/javivelasco/react-css-themr).

### Suggested solution
After several tries, the suggested solution is using **CSS variables**. This is a cross-tools solution, very clean and one that doesn't require too many changes in the library

#### Example
In the following example, you will css what changes are required and how they can be overridden

From the library side:
```css
/* Text.st.css */

:vars {
  fontsFallback: "Arial"
}

:vars {
  fontUltraThin: 'var(--fontFamilyOverride, "Helvetica", value(fontsFallback))';
}

.root {
  font-family: value(fontUltraThin);
}
```

From the consumer side:
```css
/* overridingTheme.st.css */
.root {
  --fontFamilyOverride: "sans-serif";
}
```

And all possible usages across the app:

```jsx
import React from 'react';
import Text from '../Text';
import theme from '../overridingTheme.st.css';

class App extends React.Component {
  render() {
    return (
      <div>
        <div>
          Default: <Text>Some Text</Text>
        </div>
        <div {...theme('root')}>
          Override with Stylable: <Text>Some Text</Text>
        </div>
        <div style={{ '--fontFamilyOverride': 'sans-serif' }}>
          Inline Override: <Text>Some Text</Text>
        </div>
      </div>
    );
  }
}

export default App
```

## Next steps
1. implement the CSS variable override across the library, in order to allow projects to use it
1. add `font-weight` for each font variation (should be done close to the first task)
1. improve font stack to download custom Helvetica fonts after trying the native one.
1. improve the `fontFace.css`
1. consider further improvements
